exports.el = {

    loginForm: '.login-form',
    titleText: 'h2[class="title text-center"]',
    gender: 'div[class="radio-inline"]',
    password: '#password',
    day: '#days',
    month: '#months',
    years: '#years',
    newsletter: '#newsletter',
    specialOffers: '#optin',
    firstName: '#first_name',
    lastName: '#last_name',
    company: '#company',
    ad1: '#address1',
    ad2: '#address2',
    country: '#country',
    state: '#state',
    city: '#city',
    zipcode: '#zipcode',
    number: '#mobile_number',
    buttonSignup: 'button[data-qa="create-account"]',
    buttonContinue: 'a[data-qa="continue-button"]',
    registerErrorMessage: 'form[action="/signup"] p',
}

